aws_region    = "us-east-1"
s3_bucket     = "java-app-release"
app_name      = "rose-app"
env_name      = "rose-env"
solution_stack = "64bit Amazon Linux 2023 v4.2.6 running Corretto 17"
gradle_home   = "/usr/local/gradle"
m2            = "/usr/local/apache-maven/bin"
m2_home       = "/usr/local/apache-maven"
port          = "8080"
# app_version and s3_key will be set by Jenkins
